### ISSUE TITLE
todo-list

### ISSUE THREAD

**Issue by KindaMe** [KindaMe/hangman-the-game#1]
# todo-list
### Categories
- [x] Option to choose before the game.
- [x] Edit existing.
- [x] Add your own.
- [ ] Expansion packs.
### Features
- [x] Multiword compatibility.
- [x] Special characters compatibility.
- [x] Difficulty modes.
- [ ] Pretty interface.
- [ ] And many more!
